### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mizzunet** [soumyajit4419/Portfolio#12]
```
Failed to compile
./src/components/Particle.js
Module not found: Can't resolve 'react-particles-js' in '/root/Portfolio/src/components

```
Just after running npm start

**Comment by soumyajit4419** [comment]
You can install this package using NPM.

**Comment by mizzunet** [comment]
Rooke here :D
Could you add documentation on using this template for the GitHub.io page?
By the way, this template is very much beautiful 🤩 good job
