### ISSUE TITLE
When I ran the project by typing "npm start". It is showing this error in VS Code Terminal

### ISSUE THREAD

**Issue by Kush238** [soumyajit4419/Portfolio#144]
ERROR in src\App.js
  Line 0:  Parsing error: require() of ES Module F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\eslint-scope\lib\definition.js from F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js not supported.
Instead change the require of definition.js in F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js to a dynamic import() which is available in all CommonJS modules

src\components\About\About.js
  Line 0:  Parsing error: require() of ES Module F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\eslint-scope\lib\definition.js from F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js not supported.
Instead change the require of definition.js in F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js to a dynamic import() which is available in all CommonJS modules

src\components\About\AboutCard.js
  Line 0:  Parsing error: require() of ES Module F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\eslint-scope\lib\definition.js from F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js not supported.
Instead change the require of definition.js in F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js to a dynamic import() which is available in all CommonJS modules

src\components\About\Github.js
  Line 0:  Parsing error: require() of ES Module F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\eslint-scope\lib\definition.js from F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js not supported.
Instead change the require of definition.js in F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js to a dynamic import() which is available in all CommonJS modules

src\components\About\Techstack.js
  Line 0:  Parsing error: require() of ES Module F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\eslint-scope\lib\definition.js from F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js not supported.
Instead change the require of definition.js in F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js to a dynamic import() which is available in all CommonJS modules

src\components\About\Toolstack.js
  Line 0:  Parsing error: require() of ES Module F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\eslint-scope\lib\definition.js from F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js not supported.
Instead change the require of definition.js in F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js to a dynamic import() which is available in all CommonJS modules

src\components\Footer.js
  Line 0:  Parsing error: require() of ES Module F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\eslint-scope\lib\definition.js from F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js not supported.
Instead change the require of definition.js in F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js to a dynamic import() which is available in all CommonJS modules

src\components\Home\Home.js
  Line 0:  Parsing error: require() of ES Module F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\eslint-scope\lib\definition.js from F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js not supported.
Instead change the require of definition.js in F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js to a dynamic import() which is available in all CommonJS modules

src\components\Home\Home2.js
  Line 0:  Parsing error: require() of ES Module F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\eslint-scope\lib\definition.js from F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js not supported.
Instead change the require of definition.js in F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js to a dynamic import() which is available in all CommonJS modules

src\components\Home\Type.js
  Line 0:  Parsing error: require() of ES Module F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\eslint-scope\lib\definition.js from F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js not supported.
Instead change the require of definition.js in F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js to a dynamic import() which is available in all CommonJS modules

src\components\Navbar.js
  Line 0:  Parsing error: require() of ES Module F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\eslint-scope\lib\definition.js from F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js not supported.
Instead change the require of definition.js in F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js to a dynamic import() which is available in all CommonJS modules

src\components\Particle.js
  Line 0:  Parsing error: require() of ES Module F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\eslint-scope\lib\definition.js from F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js not supported.
Instead change the require of definition.js in F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js to a dynamic import() which is available in all CommonJS modules

src\components\Pre.js
  Line 0:  Parsing error: require() of ES Module F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\eslint-scope\lib\definition.js from F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js not supported.
Instead change the require of definition.js in F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js to a dynamic import() which is available in all CommonJS modules

src\components\Projects\ProjectCards.js
  Line 0:  Parsing error: require() of ES Module F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\eslint-scope\lib\definition.js from F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js not supported.
Instead change the require of definition.js in F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js to a dynamic import() which is available in all CommonJS modules

src\components\Projects\Projects.js
  Line 0:  Parsing error: require() of ES Module F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\eslint-scope\lib\definition.js from F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js not supported.
Instead change the require of definition.js in F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js to a dynamic import() which is available in all CommonJS modules

src\components\Resume\ResumeNew.js
  Line 0:  Parsing error: require() of ES Module F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\eslint-scope\lib\definition.js from F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js not supported.
Instead change the require of definition.js in F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js to a dynamic import() which is available in all CommonJS modules

src\components\ScrollToTop.js
  Line 0:  Parsing error: require() of ES Module F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\eslint-scope\lib\definition.js from F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js not supported.
Instead change the require of definition.js in F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js to a dynamic import() which is available in all CommonJS modules

src\index.js
  Line 0:  Parsing error: require() of ES Module F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\eslint-scope\lib\definition.js from F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js not supported.
Instead change the require of definition.js in F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js to a dynamic import() which is available in all CommonJS modules

src\reportWebVitals.js
  Line 0:  Parsing error: require() of ES Module F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\eslint-scope\lib\definition.js from F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js not supported.
Instead change the require of definition.js in F:\My Portfolios\git_reactjs_portfolio\Portfolio\node_modules\babel-eslint\lib\require-from-eslint.js to a dynamic import() which is available in all CommonJS modules

**Comment by abhig1599** [comment]
install all the needed packages by typing "npm i"

**Comment by Kush238** [comment]
Yea done man <3
