### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by msadeqsirjani** [soumyajit4419/Portfolio#21]
config file in Server doesn't exist
please help me to find this file

**Comment by soumyajit4419** [comment]
This file is my own config file for connecting mongo DB. 
You can create your own config.js if you are using backend code.
Else you can ignore the server part and run only the react application

**Comment by msadeqsirjani** [comment]
ok thanks
but i need to know how pass config to mongoose
please guide me or show me sample of config with general info

**Comment by soumyajit4419** [comment]
Yes, I will attach a sample config.js file for understanding
