### ISSUE TITLE
Config File?

### ISSUE THREAD

**Issue by SiphrCodez** [soumyajit4419/Portfolio#26]
Give an example of the `config.js` file placed in server please!

**Comment by soumyajit4419** [comment]
function getSecretToken() {
  const token =
    "mongodb+srv://{username}:password@....."; // MongoDb config
    return token;
}

function getUser() {
  const userName = ""
  return userName;
}

module.exports = { getSecretToken, getUser };

**Comment by SiphrCodez** [comment]
Thank you that's all I needed!
