### ISSUE TITLE
Not able to remove Spoj & HackerRank feature.

### ISSUE THREAD

**Issue by sc4rygh0st** [soumyajit4419/Portfolio#31]
How to remove Spoj & HackerRank feature from the resume page?

is there any way to add tryhackme or hackthebox ranks?

**Comment by bpfox77** [comment]
well they won't let me purchase you a coffee as there some sort of issue with payments in and out of India apparently. FYI.

**Comment by soumyajit4419** [comment]
> well they won't let me purchase you a coffee as there some sort of issue with payments in and out of India apparently. FYI.

I am not sure but I think it's working
