### ISSUE TITLE
Typos within Leaf Disease Prediction

### ISSUE THREAD

**Issue by AdamVuu** [soumyajit4419/Portfolio#6]
![image](https://user-images.githubusercontent.com/49004242/103658305-0923bf80-4f39-11eb-9a89-e5f25cb63c2a.png)

Your are missing a space between the 'leaves' and 'The' in the phrase of '38 classes of various plant leaves.The'. Also, the word 'achive' should be spelled 'achieve'.

**Comment by AdamVuu** [comment]
I think you should capitalize 'Kaggle' to remain consistent with the rest of the paragraph as it is an organization.

**Comment by soumyajit4419** [comment]
Thanks:)
Fixed
