### ISSUE TITLE
Module parse failed: Unexpected token, You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by Bouchemel-Nasreddine** [soumyajit4419/Portfolio#71]
Hi, i've been trying to run this project on local, after typing `npm start` , i got a error saying:

./node_modules/react-activity-calendar/build/index.es.js 269:38
Module parse failed: Unexpected token (269:38)
You may need an appropriate loader to handle this file type.
|     return sum + day.count;
|   }, 0);
>   var year = getYear(parseISO(data[0]?.date));
|   var theme = getTheme(themeProp, color$1);
|   var labels = Object.assign({}, DEFAULT_LABELS, labelsProp);

**Comment by BGNepal** [comment]
I got the same issue @Bouchemel-Nasreddine were you able to find the way around.
-BG

**Comment by Bouchemel-Nasreddine** [comment]
hey @Bgorkhe , no i did not come up with a solution :'( , 

However if you fixe it in the futur somehow please share it with me, good luck

**Comment by Bgorkhe** [comment]
@Bouchemel-Nasreddine  I fixed it with the react-scripts updated to the latest version for me it was 5.0.1. That was enough.
Cheers!!
BG

**Comment by Bouchemel-Nasreddine** [comment]
apparently that solves the problem, thnx
